# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KPI-Application' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KPI-Application
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'AlamofireImage', '~> 4.0.0-beta.3'
  pod 'Charts', '~> 3.3.0'
  pod 'DynamicColor'
  pod 'MJRefresh', '~> 3.2'

end
